# Generated by Django 2.0.5 on 2018-06-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='test@example.cpm', max_length=255, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='admin', max_length=255, verbose_name='密码'),
        ),
    ]
