# Generated by Django 2.0.5 on 2018-06-19 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isAdmin',
            field=models.BooleanField(default=False, verbose_name='管理员权限'),
        ),
    ]
