# Generated by Django 2.0.5 on 2018-06-20 06:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_user_isadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='regTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='注册时间'),
            preserve_default=False,
        ),
    ]
