# Generated by Django 2.0.5 on 2018-06-20 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_user_regtime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['pubTime'], 'verbose_name': '评论'},
        ),
    ]
