# Generated by Django 2.2.2 on 2019-06-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180808_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='test@example.com', max_length=255, verbose_name='Email'),
        ),
    ]
