# Generated by Django 2.2.2 on 2019-06-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='ip',
            field=models.TextField(default='//127.0.0.1', verbose_name='IP'),
        ),
    ]
